name: CI - Build Backend

on:
  pull_request:
    branches:
      - main
    paths:
      - SecuroDoc/**
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: noto
          POSTGRES_PASSWORD: letmein1
          POSTGRES_DB: docdatabase
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    defaults:
      run:
        working-directory: ./SecuroDoc
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and run Units/Integration Tests with Maven
        run: mvn -ntp -B verify

